/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import connection.DataConnection;
import controller.ClienteCTRL;
import controller.ContatoCTRL;
import controller.EnderecoCTRL;
import controller.StatusCTRL;
import controller.TipoPessoaCTRL;
import java.awt.Rectangle;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import model.bean.Cliente;
import model.bean.Contato;
import model.bean.Endereco;
import model.bean.Status;
import model.bean.TipoPessoa;
import utils.IconManager;
import utils.ManagerJasperReport;
import utils.Utilitarios;

/**
 *
 * @author KAI
 */
public class DlgClienteNEW1 extends javax.swing.JDialog {

    private Cliente pCliente;
    private List<Contato> pContatos = new ArrayList<>();
    private List<Endereco> pEnderecos = new ArrayList<>();

    private boolean FirstRun = true;

    /**
     * Creates new form DlgClienteNEW1
     *
     * @param parent
     * @param modal
     */
    public DlgClienteNEW1(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public DlgClienteNEW1(java.awt.Frame parent, boolean modal, Cliente clnt) {
        super(parent, modal);
        initComponents();
        this.IniciaForm(clnt != null ? clnt : new Cliente(0));

        this.FirstRun = false;
    }

    public List<Contato> getpContatos() {
        return pContatos;
    }

    public void setpContatos(List<Contato> pContatos) {
        this.pContatos = pContatos;
        this.PopulaJTable_Contatos();
    }

    public List<Endereco> getpEnderecos() {
        return pEnderecos;
    }

    public void setpEnderecos(List<Endereco> pEnderecos) {
        this.pEnderecos = pEnderecos;
        this.PopulaJTable_Enderecos();
    }

    public Cliente getpCliente() {
        return pCliente;
    }

    public void setpCliente(Cliente c) {
        this.pCliente = c;
        this.PreencheComponentesComObjetoCliente();
        if (this.FirstRun) {

            this.setpContatos(ContatoCTRL.BuscarPorCliente(this.getpCliente()));
            this.PopulaJTable_Contatos();

            this.setpEnderecos(EnderecoCTRL.BuscarPorCliente(this.getpCliente()));
            this.PopulaJTable_Enderecos();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtID = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNomeFantasia_Apelido = new javax.swing.JFormattedTextField();
        txtRazaoSocial_Nome = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        txtIe_RG = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbStatus = new javax.swing.JComboBox<>();
        cbTipoPessoa = new javax.swing.JComboBox<>();
        txtDtNascimento = new com.toedter.calendar.JDateChooser();
        txtCPF = new javax.swing.JFormattedTextField();
        txtCNPJ = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtIM = new javax.swing.JFormattedTextField();
        pnlAcoes = new javax.swing.JPanel();
        btnGravar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        tpCliente = new javax.swing.JTabbedPane();
        pnlEnderecos = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEnderecos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnEnderecoIncluir = new javax.swing.JButton();
        pnlContatos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblContatos = new javax.swing.JTable();
        pnlContatosBotoes = new javax.swing.JPanel();
        btnContatoAdicionar = new javax.swing.JButton();
        btnContatoRemoverSelecionado = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cliente");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Geral"));

        jLabel1.setText("Id:");

        txtID.setEditable(false);
        txtID.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtID.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtID.setEnabled(false);

        jLabel2.setText("Nome Fantasia/Apelido:");

        jLabel3.setText("Razão Social / Nome:");

        jLabel5.setText("IE / RG:");

        jLabel7.setText("Data Nascimento:");

        jLabel8.setText("Status:");

        jLabel9.setText("Tipo:");

        cbTipoPessoa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTipoPessoaItemStateChanged(evt);
            }
        });

        try {
            txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel10.setText("CNPJ / CPF:");

        jLabel11.setText("IM:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeFantasia_Apelido))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRazaoSocial_Nome))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbTipoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtIe_RG, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtDtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtIM, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel5, jLabel7});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtDtNascimento, txtIM, txtIe_RG});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbStatus, cbTipoPessoa});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel11});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(cbTipoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNomeFantasia_Apelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtRazaoSocial_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtIe_RG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(txtCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(txtDtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(txtIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlAcoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Ações"));

        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Fechar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAcoesLayout = new javax.swing.GroupLayout(pnlAcoes);
        pnlAcoes.setLayout(pnlAcoesLayout);
        pnlAcoesLayout.setHorizontalGroup(
            pnlAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGravar, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        pnlAcoesLayout.setVerticalGroup(
            pnlAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGravar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tpCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pnlEnderecos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("*Dê duplo clique ou tecle ENTER no registro desejado para editá-lo.");

        tblEnderecos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblEnderecos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEnderecos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEnderecosMouseClicked(evt);
            }
        });
        tblEnderecos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblEnderecosKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblEnderecos);

        jButton1.setText("jButton1");

        btnEnderecoIncluir.setText("Adicionar endereço");
        btnEnderecoIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnderecoIncluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEnderecoIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton1)
                .addComponent(btnEnderecoIncluir))
        );

        javax.swing.GroupLayout pnlEnderecosLayout = new javax.swing.GroupLayout(pnlEnderecos);
        pnlEnderecos.setLayout(pnlEnderecosLayout);
        pnlEnderecosLayout.setHorizontalGroup(
            pnlEnderecosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEnderecosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEnderecosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                    .addGroup(pnlEnderecosLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlEnderecosLayout.setVerticalGroup(
            pnlEnderecosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEnderecosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tpCliente.addTab("Endereços", pnlEnderecos);

        pnlContatos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblContatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblContatos);

        btnContatoAdicionar.setText("Adicionar contato");
        btnContatoAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContatoAdicionarActionPerformed(evt);
            }
        });

        btnContatoRemoverSelecionado.setText("Remover contato selecionado");
        btnContatoRemoverSelecionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContatoRemoverSelecionadoActionPerformed(evt);
            }
        });

        jButton3.setText("jButton3");

        javax.swing.GroupLayout pnlContatosBotoesLayout = new javax.swing.GroupLayout(pnlContatosBotoes);
        pnlContatosBotoes.setLayout(pnlContatosBotoesLayout);
        pnlContatosBotoesLayout.setHorizontalGroup(
            pnlContatosBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContatosBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnContatoAdicionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnContatoRemoverSelecionado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlContatosBotoesLayout.setVerticalGroup(
            pnlContatosBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContatosBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnContatoRemoverSelecionado)
                .addComponent(btnContatoAdicionar)
                .addComponent(jButton3))
        );

        javax.swing.GroupLayout pnlContatosLayout = new javax.swing.GroupLayout(pnlContatos);
        pnlContatos.setLayout(pnlContatosLayout);
        pnlContatosLayout.setHorizontalGroup(
            pnlContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                    .addComponent(pnlContatosBotoes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlContatosLayout.setVerticalGroup(
            pnlContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlContatosBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tpCliente.addTab("Contatos", pnlContatos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tpCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tpCliente)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbTipoPessoaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTipoPessoaItemStateChanged

        int eixoX = txtIM.getX();
        int eixoY = txtIe_RG.getY();
        Rectangle rectAtctive = new Rectangle(eixoX, eixoY, 200, txtIM.getHeight());
        Rectangle rectInatctive = new Rectangle(eixoX, eixoY, 0, txtIM.getHeight());

        jPanel1.remove(txtCNPJ);
        jPanel1.remove(txtCPF);

        if (cbTipoPessoa.getSelectedItem().toString().endsWith("sica")) {
            txtCPF.setEnabled(true);
            txtCNPJ.setEnabled(false);
            txtDtNascimento.setEnabled(true);
            txtCPF.setBounds(rectAtctive);
            txtCNPJ.setBounds(rectInatctive);
            jPanel1.add(txtCPF);
            this.HabilitaTXT_CNPJ_CPF(false, true);
        } else {
            txtCPF.setEnabled(false);
            txtCNPJ.setEnabled(true);
            txtDtNascimento.setEnabled(false);
            txtCPF.setBounds(rectInatctive);
            txtCNPJ.setBounds(rectAtctive);
            jPanel1.add(txtCNPJ);
            this.HabilitaTXT_CNPJ_CPF(true, false);
        }
    }//GEN-LAST:event_cbTipoPessoaItemStateChanged
    private void HabilitaTXT_CNPJ_CPF(boolean cnpj_, boolean cpf_) {
        txtCNPJ.setEnabled(cnpj_);

        txtCPF.setEnabled(cpf_);
    }
    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        this.PreencheObjetoClienteComValoresDosComponentes();

        this.setpCliente(ClienteCTRL.Gravar(this.getpCliente(), null));
        this.PersistirContatos();
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnContatoRemoverSelecionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContatoRemoverSelecionadoActionPerformed
        this.ContatoExcluir((int) tblContatos.getValueAt(tblContatos.getSelectedRow(), 0));
    }//GEN-LAST:event_btnContatoRemoverSelecionadoActionPerformed

    private void btnContatoAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContatoAdicionarActionPerformed
        this.ContatoAdicionar();
    }//GEN-LAST:event_btnContatoAdicionarActionPerformed

    private void btnEnderecoIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnderecoIncluirActionPerformed
        this.ShowFormEndereco(new Endereco(0, this.getpCliente()));
        this.setpEnderecos(EnderecoCTRL.BuscarPorCliente(this.getpCliente()));
        this.PopulaJTable_Enderecos();
    }//GEN-LAST:event_btnEnderecoIncluirActionPerformed

    private void tblEnderecosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblEnderecosKeyPressed
        if ((evt.getKeyChar() == KeyEvent.VK_ENTER)) {
            this.RetornaEnderecoSelecionado();
            evt.consume();
        }
    }//GEN-LAST:event_tblEnderecosKeyPressed

    private void tblEnderecosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEnderecosMouseClicked
        if (evt.getClickCount() == 2) {
            this.RetornaEnderecoSelecionado();
        }
    }//GEN-LAST:event_tblEnderecosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgClienteNEW1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            DlgClienteNEW1 dialog = new DlgClienteNEW1(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnContatoAdicionar;
    private javax.swing.JButton btnContatoRemoverSelecionado;
    private javax.swing.JButton btnEnderecoIncluir;
    private javax.swing.JButton btnGravar;
    private javax.swing.JComboBox<model.bean.Status> cbStatus;
    private javax.swing.JComboBox<model.bean.TipoPessoa> cbTipoPessoa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlAcoes;
    private javax.swing.JPanel pnlContatos;
    private javax.swing.JPanel pnlContatosBotoes;
    private javax.swing.JPanel pnlEnderecos;
    private javax.swing.JTable tblContatos;
    private javax.swing.JTable tblEnderecos;
    private javax.swing.JTabbedPane tpCliente;
    private javax.swing.JFormattedTextField txtCNPJ;
    private javax.swing.JFormattedTextField txtCPF;
    private com.toedter.calendar.JDateChooser txtDtNascimento;
    private javax.swing.JFormattedTextField txtID;
    private javax.swing.JFormattedTextField txtIM;
    private javax.swing.JFormattedTextField txtIe_RG;
    private javax.swing.JFormattedTextField txtNomeFantasia_Apelido;
    private javax.swing.JFormattedTextField txtRazaoSocial_Nome;
    // End of variables declaration//GEN-END:variables

    private void IniciaForm(Cliente c) {
        StatusCTRL.BuscaTodos().forEach((Status sts) -> {
            cbStatus.addItem(sts);
        });

        TipoPessoaCTRL.BuscaTodos().forEach((TipoPessoa tpPess) -> {
            cbTipoPessoa.addItem(tpPess);
        });

        this.setpCliente(c);

        cbTipoPessoa.setEnabled(this.getpCliente().IsNew());

        new IconManager().SetaIcones(new JButton[]{btnGravar, btnCancelar, btnEnderecoIncluir});

        Utilitarios.RePosicionaBotoes(new JButton[]{btnContatoAdicionar, btnContatoRemoverSelecionado}, pnlContatosBotoes, 250, true);

        this.PopulaJTable_Contatos();

        this.PopulaJTable_Enderecos();
    }

    private void PreencheComponentesComObjetoCliente() {
        txtID.setText(String.valueOf(this.getpCliente().getId()));
        txtNomeFantasia_Apelido.setText(this.getpCliente().getNomeFantasia_Apelido());

        if (this.getpCliente().getStatus() != null && this.getpCliente().getTipoPessoa() != null) {
            Utilitarios.SetItemSelectedComboBox(
                    new JComboBox[]{cbStatus, cbTipoPessoa},
                    new String[]{
                        this.getpCliente().getStatus().getDescricao(),
                        this.getpCliente().getTipoPessoa() != null ? this.getpCliente().getTipoPessoa().getDescricao() : "Pessoa Juridica"
                    }
            );
        }

        if (cbTipoPessoa.getSelectedItem().toString().endsWith("sica")) {
            txtCPF.setText(this.getpCliente().getCNPJ_CPF());
            txtDtNascimento.setDate(this.getpCliente().getDataNascimento());
        } else {
            txtCNPJ.setText(this.getpCliente().getCNPJ_CPF());
        }

        txtIM.setText(this.getpCliente().getIM());
        txtIe_RG.setText(this.getpCliente().getIE_RG());
        txtRazaoSocial_Nome.setText(this.getpCliente().getRazaoSocial_Nome());
    }

    private void PreencheObjetoClienteComValoresDosComponentes() {

        if (cbTipoPessoa.getSelectedItem().toString().endsWith("sica")) {
            this.getpCliente().setCNPJ_CPF(txtCPF.getText());
            this.getpCliente().setDataNascimento(txtDtNascimento.getDate());
        } else {
            this.getpCliente().setCNPJ_CPF(txtCNPJ.getText());
        }
        this.getpCliente().setIE_RG(txtIe_RG.getText());
        this.getpCliente().setIM(txtIM.getText());
        this.getpCliente().setNomeFantasia_Apelido(txtNomeFantasia_Apelido.getText());
        this.getpCliente().setRazaoSocial_Nome(txtRazaoSocial_Nome.getText());
        this.getpCliente().setStatus((Status) cbStatus.getSelectedItem());
        this.getpCliente().setTipoPessoa((TipoPessoa) cbTipoPessoa.getSelectedItem());
        this.getpCliente().setId(Integer.valueOf(txtID.getText()));
    }

    private void PopulaJTable_Contatos() {
//        this.setpContatos(ContatoCTRL.BuscarPorCliente(this.getpCliente()));
        List<Contato> ContatosLocal = this.getpContatos();

        String[] colunas = "Id,Descrição".split(",");

        Object[][] dados = new Object[ContatosLocal.size()][colunas.length];
        for (int linha = 0; linha < ContatosLocal.size(); linha++) {
            int coluna = 0;
            dados[linha][coluna++] = ContatosLocal.get(linha).getId();
            dados[linha][coluna++] = ContatosLocal.get(linha).getDescricao();
        }
        DefaultTableModel mdl = new DefaultTableModel(dados, colunas) {
            boolean[] canEdit = new boolean[]{
                false, true
            };

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };
        tblContatos.setModel(mdl);
        tblContatos.setAutoCreateRowSorter(true);
        tblContatos.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tblContatos.setShowGrid(true);
        tblContatos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        int xx = 0;
        tblContatos.getColumnModel().getColumn(xx++).setPreferredWidth((int) (tblContatos.getParent().getWidth() * 0.08));
        tblContatos.getColumnModel().getColumn(xx++).setPreferredWidth((int) (tblContatos.getParent().getWidth() * 0.85));
    }

    private void ContatoAdicionar() {
        this.pContatos.removeAll(this.getpContatos());

        List<Contato> ContatosLocal = new ArrayList<>();
        for (int x_ = 0; x_ < tblContatos.getRowCount(); x_++) {
            ContatosLocal.add(
                    new Contato(
                            (int) tblContatos.getValueAt(x_, 0),
                            String.valueOf(tblContatos.getValueAt(x_, 1)),
                            this.getpCliente()
                    )
            );
        }
        ContatosLocal.add(new Contato(0, "", this.getpCliente()));
        this.setpContatos(ContatosLocal);
    }

    private void PersistirContatos() {
        this.getpContatos().removeAll(this.getpContatos());
        for (int i = 0; i < tblContatos.getRowCount(); i++) {
            String ContatoDescricao_ = String.valueOf(tblContatos.getValueAt(i, 1)).concat("").trim();
            if (ContatoDescricao_.length() > 0) {
                Contato c_ = new Contato(
                        (int) tblContatos.getValueAt(i, 0),
                        String.valueOf(tblContatos.getValueAt(i, 1)).concat(""),
                        this.getpCliente()
                );
                ContatoCTRL.Gravar(c_);
            }
        }
        this.setpContatos(ContatoCTRL.BuscarPorCliente(this.getpCliente()));
        this.PopulaJTable_Contatos();
    }

    private void ContatoExcluir(int id_) {
        if (JOptionPane.showConfirmDialog(null, "Deseja realmente excluir o registro de Contato(" + id_ + ")?", "<<< Atenção! >>>?", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            ContatoCTRL.Deletar(new Contato(id_));
            this.setpContatos(ContatoCTRL.BuscarPorCliente(this.getpCliente()));
            this.PopulaJTable_Contatos();
        }
    }

    private void PopulaJTable_Enderecos() {
        List<Endereco> EnderecosLocal = this.getpEnderecos();

        String[] colunas = "Id,CEP,Logradouro,Complemento,Nr,Cidade,UF,Bairro,Latitude,Longitude".split(",");

        Object[][] dados = new Object[EnderecosLocal.size()][colunas.length];
        for (int linha = 0; linha < EnderecosLocal.size(); linha++) {
            int coluna = 0;
            dados[linha][coluna++] = EnderecosLocal.get(linha).getId();//0
            dados[linha][coluna++] = EnderecosLocal.get(linha).getCEP();//1
            dados[linha][coluna++] = EnderecosLocal.get(linha).getLogradouro();//2
            dados[linha][coluna++] = EnderecosLocal.get(linha).getComplemento();//3
            dados[linha][coluna++] = EnderecosLocal.get(linha).getNumero();//4
            dados[linha][coluna++] = EnderecosLocal.get(linha).getCidade();//5
            dados[linha][coluna++] = EnderecosLocal.get(linha).getUF();//6
            dados[linha][coluna++] = EnderecosLocal.get(linha).getBairro();//7
            dados[linha][coluna++] = EnderecosLocal.get(linha).getLatitude();//8
            dados[linha][coluna++] = EnderecosLocal.get(linha).getLongitude();//9
        }
        DefaultTableModel mdl = new DefaultTableModel(dados, colunas) {
            boolean[] canEdit = new boolean[]{
                false, false, false, false, false, false, false, false, false, false
            };

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };
        JTable tbl_ = tblEnderecos;
        tbl_.setModel(mdl);
        tbl_.setAutoCreateRowSorter(true);
        tbl_.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tbl_.setShowGrid(true);
        tbl_.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        int xx = 0;
        tbl_.getColumnModel().getColumn(xx++).setPreferredWidth((int) (tbl_.getParent().getWidth() * 0.03));//0
        tbl_.getColumnModel().getColumn(xx++).setPreferredWidth((int) (tbl_.getParent().getWidth() * 0.10));//1
        tbl_.getColumnModel().getColumn(xx++).setPreferredWidth((int) (tbl_.getParent().getWidth() * 0.22));//2
        tbl_.getColumnModel().getColumn(xx++).setPreferredWidth((int) (tbl_.getParent().getWidth() * 0.18));//3
        tbl_.getColumnModel().getColumn(xx++).setPreferredWidth((int) (tbl_.getParent().getWidth() * 0.04));//4
        tbl_.getColumnModel().getColumn(xx++).setPreferredWidth((int) (tbl_.getParent().getWidth() * 0.13));//5
        tbl_.getColumnModel().getColumn(xx++).setPreferredWidth((int) (tbl_.getParent().getWidth() * 0.03));//6
        tbl_.getColumnModel().getColumn(xx++).setPreferredWidth((int) (tbl_.getParent().getWidth() * 0.10));//7
        tbl_.getColumnModel().getColumn(xx++).setPreferredWidth((int) (tbl_.getParent().getWidth() * 0.08));//8
        tbl_.getColumnModel().getColumn(xx++).setPreferredWidth((int) (tbl_.getParent().getWidth() * 0.08));//9
    }

    private void ShowFormEndereco(Endereco e) {
        e.setCliente(this.getpCliente());
        DlgEnderecos dlg = new DlgEnderecos(null, true, e);
        dlg.setVisible(true);
        dlg.toFront();
    }

    private void RetornaEnderecoSelecionado() {
        Endereco e = EnderecoCTRL.BuscarPorID((int) tblEnderecos.getValueAt(tblEnderecos.getSelectedRow(), 0));
        e.setCliente(this.getpCliente());
        this.ShowFormEndereco(e);

        this.setpEnderecos(EnderecoCTRL.BuscarPorCliente(this.getpCliente()));
    }

}
