/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ClienteCTRL;
import controller.ContatoCTRL;
import controller.EnderecoCTRL;
import controller.StatusCTRL;
import controller.TipoPessoaCTRL;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import model.bean.Cliente;
import model.bean.Contato;
import model.bean.Endereco;
import model.bean.Status;
import model.bean.TipoPessoa;
import utils.Enumeradors;
import utils.Utilitarios;

/**
 *
 * @author KAI
 */
public class DlgCliente extends javax.swing.JDialog {

    private boolean FirstRun = true;
    private Cliente ClienteSelecionado = new Cliente();
    private List<Cliente> ClientesListaPesquisa = new ArrayList<>();
    private Endereco EnderecoSelecionado = null;

    /**
     * Creates new form DlgCliente
     *
     * @param parent
     * @param modal
     */
    public DlgCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.IniciaForm();
        this.FirstRun = false;
    }

    public Cliente getClienteSelecionado() {
        return ClienteSelecionado;
    }

    public void setClienteSelecionado(/*Cliente ClienteSelecionado*/) {
        for (int i = 0; i < this.ClientesListaPesquisa.size(); i++) {
            if (this.ClientesListaPesquisa.get(i).getId() == (int) tblClientes.getValueAt(tblClientes.getSelectedRow(), 0)) {
                this.ClienteSelecionado = this.ClientesListaPesquisa.get(i);
                break;
            }
        }

        this.ClienteSelecionado.setEnderecos(EnderecoCTRL.BuscarPorCliente(ClienteSelecionado));
        this.ClienteSelecionado.setContatos(ContatoCTRL.BuscarPorCliente(ClienteSelecionado));

        this.PopulaComponentesCliente();

        this.PopulaJTableEndereco();
        this.PopulaJTableContato();

    }

    public List<Cliente> getClientesListaPesquisa() {
        return ClientesListaPesquisa;
    }

    public void setClientesListaPesquisa(List<Cliente> ClientesListaPesquisa) {
        this.ClientesListaPesquisa = ClientesListaPesquisa;
    }

    public Endereco getEnderecoSelecionado() {
        return EnderecoSelecionado;
    }

    public void setEnderecoSelecionado(/*Endereco EnderecoSelecionado*/) {
//        this.EnderecoSelecionado = EnderecoSelecionado;
        for (int i = 0; i < this.ClienteSelecionado.getEnderecos().size(); i++) {
            if (this.ClienteSelecionado.getEnderecos().get(i).getId() == (int) tblEndereco.getValueAt(tblEndereco.getSelectedRow(), 0)) {
                this.EnderecoSelecionado = this.ClienteSelecionado.getEnderecos().get(i);
                break;
            }
        }
        this.PopulaComponentesEndereco();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        pnlBotoes = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnGravar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        pnlPesquisaCliente = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        spnrQtdeMaxCliente = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        cmbxCampoPesquisaCliente = new javax.swing.JComboBox<>();
        txtConteudoPesquisaCliente = new javax.swing.JFormattedTextField();
        btnLocalizarCliente = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        tbpnMain = new javax.swing.JTabbedPane();
        pnlGeral = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNomeFantasia_Apelido = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        txtRazaoSocial_Nome = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        txtIE_RG = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIM = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cmbxStatus = new javax.swing.JComboBox<>();
        cmbxTipoPessoa = new javax.swing.JComboBox<>();
        txtDataNascimento = new com.toedter.calendar.JDateChooser();
        txtCNPJ_CPF = new javax.swing.JFormattedTextField();
        pnlEnderecos = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtCEP = new javax.swing.JFormattedTextField();
        txtLogradouro = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtComplemento = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        txtCidade = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JFormattedTextField();
        cmbxUF = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEndereco = new javax.swing.JTable();
        btnIncluirEndereco = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        pnlContatos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblContato = new javax.swing.JTable();
        btnIncluirContato = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cliente");
        setResizable(false);

        pnlMain.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pnlBotoes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBotoesLayout = new javax.swing.GroupLayout(pnlBotoes);
        pnlBotoes.setLayout(pnlBotoesLayout);
        pnlBotoesLayout.setHorizontalGroup(
            pnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNovo)
                .addGap(18, 18, 18)
                .addComponent(btnGravar)
                .addGap(18, 18, 18)
                .addComponent(btnFechar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlBotoesLayout.setVerticalGroup(
            pnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnNovo)
                    .addComponent(btnGravar)
                    .addComponent(btnFechar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlPesquisaCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientesMouseClicked(evt);
            }
        });
        tblClientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblClientesKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(tblClientes);

        jLabel14.setText("Máximo:");

        spnrQtdeMaxCliente.setModel(new javax.swing.SpinnerNumberModel(10, 1, 100, 1));

        jLabel15.setText("Campo:");

        cmbxCampoPesquisaCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome" }));

        txtConteudoPesquisaCliente.setText("%");

        btnLocalizarCliente.setText("Localizar");
        btnLocalizarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocalizarClienteActionPerformed(evt);
            }
        });

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Tecle ENTER ou dê um duplo clique no registro abaixo para pode editá-lo.");

        javax.swing.GroupLayout pnlPesquisaClienteLayout = new javax.swing.GroupLayout(pnlPesquisaCliente);
        pnlPesquisaCliente.setLayout(pnlPesquisaClienteLayout);
        pnlPesquisaClienteLayout.setHorizontalGroup(
            pnlPesquisaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPesquisaClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPesquisaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addGroup(pnlPesquisaClienteLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnrQtdeMaxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbxCampoPesquisaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtConteudoPesquisaCliente)
                        .addGap(18, 18, 18)
                        .addComponent(btnLocalizarCliente)))
                .addContainerGap())
        );
        pnlPesquisaClienteLayout.setVerticalGroup(
            pnlPesquisaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPesquisaClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPesquisaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(spnrQtdeMaxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(cmbxCampoPesquisaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConteudoPesquisaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLocalizarCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbpnMain.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pnlGeral.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Id:");

        txtId.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtId.setEnabled(false);

        jLabel2.setText("Nome Fantasia / Apelido:");

        jLabel3.setText("CNPJ / CPF:");

        jLabel4.setText("Razão Social / Nome:");

        txtIE_RG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIE_RGActionPerformed(evt);
            }
        });

        jLabel5.setText("I.E. / R.G.:");

        jLabel6.setText("I.M.:");

        txtIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIMActionPerformed(evt);
            }
        });

        jLabel7.setText("Data Nascimento:");

        jLabel8.setText("Status:");

        jLabel9.setText("Tipo Pessoa:");

        cmbxTipoPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbxTipoPessoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlGeralLayout = new javax.swing.GroupLayout(pnlGeral);
        pnlGeral.setLayout(pnlGeralLayout);
        pnlGeralLayout.setHorizontalGroup(
            pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGeralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlGeralLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeFantasia_Apelido))
                    .addGroup(pnlGeralLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRazaoSocial_Nome))
                    .addGroup(pnlGeralLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCNPJ_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIE_RG))
                    .addGroup(pnlGeralLayout.createSequentialGroup()
                        .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlGeralLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlGeralLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbxTipoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addGroup(pnlGeralLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIM, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDataNascimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pnlGeralLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel6, jLabel9});

        pnlGeralLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel5, jLabel7, jLabel8});

        pnlGeralLayout.setVerticalGroup(
            pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGeralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(cmbxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cmbxTipoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNomeFantasia_Apelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtRazaoSocial_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(txtIE_RG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCNPJ_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addComponent(txtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        tbpnMain.addTab("Geral", pnlGeral);

        pnlEnderecos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setText("CEP:");

        jLabel11.setText("Logradouro:");

        jLabel12.setText("UF:");

        jLabel13.setText("Complemento:");

        jLabel16.setText("Cidade:");

        jLabel17.setText("Número:");

        cmbxUF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbxUFActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblEndereco.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblEndereco.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEndereco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEnderecoMouseClicked(evt);
            }
        });
        tblEndereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblEnderecoKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblEndereco);

        btnIncluirEndereco.setText("Incluir endereço");

        jLabel19.setText("Para alterar o registro tecle ENTER dou dê um duplo clique com o botão normal do mouse sobre a linha desejada.");
        jLabel19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnIncluirEndereco)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIncluirEndereco)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlEnderecosLayout = new javax.swing.GroupLayout(pnlEnderecos);
        pnlEnderecos.setLayout(pnlEnderecosLayout);
        pnlEnderecosLayout.setHorizontalGroup(
            pnlEnderecosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEnderecosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEnderecosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEnderecosLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbxUF, 0, 54, Short.MAX_VALUE))
                    .addGroup(pnlEnderecosLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtComplemento)))
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlEnderecosLayout.setVerticalGroup(
            pnlEnderecosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEnderecosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEnderecosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEnderecosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17)
                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlEnderecosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(cmbxUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEnderecosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tbpnMain.addTab("Endereços", pnlEnderecos);

        pnlContatos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblContato.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblContato.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblContato);

        btnIncluirContato.setText("Incluir contato");
        btnIncluirContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirContatoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlContatosLayout = new javax.swing.GroupLayout(pnlContatos);
        pnlContatos.setLayout(pnlContatosLayout);
        pnlContatosLayout.setHorizontalGroup(
            pnlContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
                    .addGroup(pnlContatosLayout.createSequentialGroup()
                        .addComponent(btnIncluirContato)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlContatosLayout.setVerticalGroup(
            pnlContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIncluirContato)
                .addContainerGap())
        );

        tbpnMain.addTab("Contatos", pnlContatos);

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tbpnMain)
                    .addComponent(pnlBotoes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPesquisaCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbpnMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPesquisaCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtIE_RGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIE_RGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIE_RGActionPerformed

    private void cmbxTipoPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxTipoPessoaActionPerformed
        this.IsFP();
    }//GEN-LAST:event_cmbxTipoPessoaActionPerformed

    private void txtIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIMActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnLocalizarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocalizarClienteActionPerformed
        this.PopulaJTableCliente();
    }//GEN-LAST:event_btnLocalizarClienteActionPerformed

    private void tblClientesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblClientesKeyPressed
        if ((evt.getKeyChar() == KeyEvent.VK_ENTER)) {
            this.setClienteSelecionado();
            evt.consume();
        }
    }//GEN-LAST:event_tblClientesKeyPressed

    private void tblClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientesMouseClicked
        if (evt.getClickCount() == 2) {
            this.setClienteSelecionado();
        }
    }//GEN-LAST:event_tblClientesMouseClicked

    private void tblEnderecoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblEnderecoKeyPressed
        if ((evt.getKeyChar() == KeyEvent.VK_ENTER)) {
            this.setEnderecoSelecionado();
            evt.consume();
        }

    }//GEN-LAST:event_tblEnderecoKeyPressed

    private void tblEnderecoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEnderecoMouseClicked
        if (evt.getClickCount() == 2) {
            this.setEnderecoSelecionado();
        }
    }//GEN-LAST:event_tblEnderecoMouseClicked

    private void btnIncluirContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirContatoActionPerformed
        List<Contato> contatos = ClienteSelecionado.getContatos();
        contatos.add(new Contato());
        PopulaJTableContato();
    }//GEN-LAST:event_btnIncluirContatoActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        this.PersistirCliente();
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        this.ClienteSelecionado = new Cliente();
        this.setClienteSelecionado();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void cmbxUFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxUFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbxUFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            DlgCliente dialog = new DlgCliente(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnIncluirContato;
    private javax.swing.JButton btnIncluirEndereco;
    private javax.swing.JButton btnLocalizarCliente;
    private javax.swing.JButton btnNovo;
    private javax.swing.JComboBox<String> cmbxCampoPesquisaCliente;
    private javax.swing.JComboBox<Object> cmbxStatus;
    public javax.swing.JComboBox<model.bean.TipoPessoa> cmbxTipoPessoa;
    private javax.swing.JComboBox<Enumeradors.UF> cmbxUF;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel pnlBotoes;
    private javax.swing.JPanel pnlContatos;
    private javax.swing.JPanel pnlEnderecos;
    private javax.swing.JPanel pnlGeral;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlPesquisaCliente;
    private javax.swing.JSpinner spnrQtdeMaxCliente;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTable tblContato;
    private javax.swing.JTable tblEndereco;
    private javax.swing.JTabbedPane tbpnMain;
    private javax.swing.JFormattedTextField txtCEP;
    private javax.swing.JFormattedTextField txtCNPJ_CPF;
    private javax.swing.JFormattedTextField txtCidade;
    private javax.swing.JFormattedTextField txtComplemento;
    private javax.swing.JFormattedTextField txtConteudoPesquisaCliente;
    private com.toedter.calendar.JDateChooser txtDataNascimento;
    private javax.swing.JFormattedTextField txtIE_RG;
    private javax.swing.JFormattedTextField txtIM;
    private javax.swing.JFormattedTextField txtId;
    private javax.swing.JFormattedTextField txtLogradouro;
    private javax.swing.JFormattedTextField txtNomeFantasia_Apelido;
    private javax.swing.JFormattedTextField txtNumero;
    private javax.swing.JFormattedTextField txtRazaoSocial_Nome;
    // End of variables declaration//GEN-END:variables

    private void IniciaForm() {
        StatusCTRL.BuscaTodos().forEach((Status sts) -> {
            cmbxStatus.addItem(sts);
        });
//        cmbxStatus.setSelectedIndex(-1);

        TipoPessoaCTRL.BuscaTodos().forEach((TipoPessoa tp) -> {
            cmbxTipoPessoa.addItem(tp);
        });
//        cmbxTipoPessoa.setSelectedIndex(-1);

        for (Enumeradors.UF value : Enumeradors.UF.values()) {
            cmbxUF.addItem(value);
        }
//        cmbxUF.setSelectedIndex(-1);

        Utilitarios.RePosicionaBotoes(new JButton[]{btnNovo, btnGravar, btnFechar}, pnlBotoes, 150);

        this.PopulaJTableCliente();
        this.PopulaJTableEndereco();
        this.PopulaJTableContato();
    }

    private void PopulaJTableCliente() {
        String[] colunas = new String[]{"Id", "Nome", "Tipo", "CNPJ/CPF", "Status"};
        int QtdeRegistros = 0;
        this.ClienteSelecionado = null;
        this.ClientesListaPesquisa.removeAll(this.ClientesListaPesquisa);
        if (!FirstRun) {
            if (txtConteudoPesquisaCliente.getText().trim().length() > 0) {
//                System.out.println(new Date());
                this.setClientesListaPesquisa(ClienteCTRL.BuscarPorNome((int) spnrQtdeMaxCliente.getValue(), txtConteudoPesquisaCliente.getText(), null));
//                System.out.println(new Date());
                QtdeRegistros = this.ClientesListaPesquisa.size();
            } else {
                JOptionPane.showMessageDialog(null, "Digite alguma informação para a pesquisa!", "<<<ATENÇÃO>>>", 2);
            }
        } else {
            this.ClienteSelecionado = new Cliente();
        }

        Object[][] dados = new Object[QtdeRegistros][colunas.length];

        for (int linha = 0; linha < QtdeRegistros; linha++) {
            int coluna = 0;
            dados[linha][coluna++] = this.ClientesListaPesquisa.get(linha).getId();
            dados[linha][coluna++] = this.ClientesListaPesquisa.get(linha).getRazaoSocial_Nome();
            dados[linha][coluna++] = this.ClientesListaPesquisa.get(linha).getTipoPessoa();
            dados[linha][coluna++] = this.ClientesListaPesquisa.get(linha).getCNPJ_CPF();
            dados[linha][coluna++] = this.ClientesListaPesquisa.get(linha).getStatus();
        }

        DefaultTableModel mdl = new DefaultTableModel(dados, colunas) {
            boolean[] canEdit = new boolean[]{
                false, false, false, false, false
            };

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };
        tblClientes.setModel(mdl);
        tblClientes.setAutoCreateRowSorter(true);
        tblClientes.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblClientes.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tblClientes.setShowGrid(true);
        tblClientes.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblClientes.getColumnModel().getColumn(0).setPreferredWidth(50);
        tblClientes.getColumnModel().getColumn(1).setPreferredWidth(tblClientes.getWidth() - 50 - 100 - 130 - 50);
        tblClientes.getColumnModel().getColumn(2).setPreferredWidth(100);
        tblClientes.getColumnModel().getColumn(3).setPreferredWidth(130);
        tblClientes.getColumnModel().getColumn(4).setPreferredWidth(50);
    }

    private void PopulaJTableEndereco() {
        String[] colunas = new String[]{"Id", "CEP", "Cidade", "UF"};

        List<Endereco> enderecos = FirstRun ? new ArrayList<>() : this.getClienteSelecionado().getEnderecos();
        int QtdeRegistros = FirstRun ? 0 : enderecos.size();

        Object[][] dados = new Object[QtdeRegistros][colunas.length];

        for (int linha = 0; linha < QtdeRegistros; linha++) {
            int coluna = 0;
            dados[linha][coluna++] = enderecos.get(linha).getId();
            dados[linha][coluna++] = enderecos.get(linha).getCEP();
            dados[linha][coluna++] = enderecos.get(linha).getCidade();
            dados[linha][coluna++] = enderecos.get(linha).getUF();
        }

        DefaultTableModel mdl = new DefaultTableModel(dados, colunas) {
            boolean[] canEdit = new boolean[]{
                false, false, false, false
            };

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };
        tblEndereco.setModel(mdl);
        tblEndereco.setAutoCreateRowSorter(true);
        tblEndereco.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tblEndereco.setShowGrid(true);
        tblEndereco.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblEndereco.getColumnModel().getColumn(0).setPreferredWidth(35);
        tblEndereco.getColumnModel().getColumn(0).setPreferredWidth(35);

    }

    private void PopulaJTableContato() {
        String[] colunas = new String[]{"Id", "Descrição"};

        List<Contato> contatos = FirstRun ? new ArrayList<>() : this.getClienteSelecionado().getContatos();
        int QtdeRegistros = FirstRun ? 0 : contatos.size();

        Object[][] dados = new Object[QtdeRegistros][colunas.length];

        for (int linha = 0; linha < QtdeRegistros; linha++) {
            int coluna = 0;
            dados[linha][coluna++] = contatos.get(linha).getId();
            dados[linha][coluna++] = contatos.get(linha).getDescricao();
        }

        DefaultTableModel mdl = new DefaultTableModel(dados, colunas) {
            boolean[] canEdit = new boolean[]{
                false, true
            };

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };
        tblContato.setModel(mdl);
        tblContato.setAutoCreateRowSorter(true);
        tblContato.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tblContato.setShowGrid(true);
        tblContato.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblContato.getColumnModel().getColumn(0).setPreferredWidth(65);
        tblContato.getColumnModel().getColumn(1).setPreferredWidth(tblContato.getWidth() - 65);
    }

    private void PopulaComponentesCliente() {
        txtId.setText(String.valueOf(this.getClienteSelecionado().getId()));
        txtNomeFantasia_Apelido.setText(this.getClienteSelecionado().getNomeFantasia_Apelido());
        txtRazaoSocial_Nome.setText(this.getClienteSelecionado().getRazaoSocial_Nome());
        txtIE_RG.setText(this.getClienteSelecionado().getIE_RG());
        txtIM.setText(this.getClienteSelecionado().getIM());

        if (!this.ClienteSelecionado.IsNew()) {
            Utilitarios.SetItemSelectedComboBox(
                    new JComboBox[]{cmbxStatus, cmbxTipoPessoa},
                    new String[]{
                        this.getClienteSelecionado().getStatus().getDescricao(),
                        this.getClienteSelecionado().getTipoPessoa().getDescricao()
                    }
            );
        }

        cmbxTipoPessoa.setEnabled(this.getClienteSelecionado().IsNew());

        txtCNPJ_CPF.setText(this.getClienteSelecionado().getCNPJ_CPF());

    }

    private void PopulaComponentesEndereco() {
        txtCEP.setText(EnderecoSelecionado.getCEP());
        txtNumero.setText(EnderecoSelecionado.getNumero());
        txtCidade.setText(EnderecoSelecionado.getCidade());
        txtLogradouro.setText(EnderecoSelecionado.getLogradouro());
        txtComplemento.setText(EnderecoSelecionado.getComplemento());
        Utilitarios.SetItemSelectedComboBox(new JComboBox[]{cmbxUF}, new String[]{EnderecoSelecionado.getUF().toString()});
    }

    private void IsFP() {

        Enumeradors.TiposMascarados tpMascara = null;
        try {
            if (this.getClienteSelecionado().getTipoPessoa() != null) {
                if (this.getClienteSelecionado().getTipoPessoa().getDescricao().endsWith("sica")) {
                    txtDataNascimento.setDate(this.getClienteSelecionado().getDataNascimento());
                    txtDataNascimento.setEnabled(true);
                    tpMascara = Enumeradors.TiposMascarados.PessoaFisica;
                } else {
                    txtDataNascimento.setEnabled(false);
                    tpMascara = Enumeradors.TiposMascarados.PessoaJuridica;
                }
            }

            if (cmbxTipoPessoa.getSelectedItem() != null) {
                if (cmbxTipoPessoa.getSelectedItem().toString().endsWith("sica")) {
                    txtDataNascimento.setDate(this.getClienteSelecionado().getDataNascimento());
                    txtDataNascimento.setEnabled(true);
                    tpMascara = Enumeradors.TiposMascarados.PessoaFisica;
                } else {
                    txtDataNascimento.setEnabled(false);
                    tpMascara = Enumeradors.TiposMascarados.PessoaJuridica;
                }
            }
        } catch (Exception e) {
            System.out.println("Erro ao tentar identificar TipoPessoa: " + e);
        }

//        System.out.println("0: " + tpMascara);
        if (tpMascara != null) {
            try {
                txtCNPJ_CPF.setFormatterFactory(
                        new javax.swing.text.DefaultFormatterFactory(
                                new javax.swing.text.MaskFormatter(
                                        tpMascara.equals(Enumeradors.TiposMascarados.PessoaJuridica)
                                        ? "##.###.###/####-##"
                                        : "###.###.###-##"
                                )
                        )
                );
            } catch (ParseException ex) {
                System.out.println("Erro ao tentar mascarar dado (" + tpMascara.toString() + "): " + ex);
                Logger.getLogger(DlgCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private void PersistirCliente() {
        this.PopulaObjClienteComInfosComponentes();
        this.ClienteSelecionado = ClienteCTRL.Gravar(this.ClienteSelecionado, null);
        this.setClienteSelecionado();
    }

    private void PopulaObjClienteComInfosComponentes() {
        this.ClienteSelecionado.setCNPJ_CPF(txtCNPJ_CPF.getText());
        this.ClienteSelecionado.setDataNascimento((Date) txtDataNascimento.getDate());
        this.ClienteSelecionado.setIE_RG(txtIE_RG.getText());
        this.ClienteSelecionado.setIM(txtIM.getText());
        this.ClienteSelecionado.setNomeFantasia_Apelido(txtNomeFantasia_Apelido.getText());
        this.ClienteSelecionado.setRazaoSocial_Nome(txtRazaoSocial_Nome.getText());
        this.ClienteSelecionado.setStatus((Status) cmbxStatus.getSelectedItem());
        this.ClienteSelecionado.setTipoPessoa((TipoPessoa) cmbxTipoPessoa.getSelectedItem());
        this.ClienteSelecionado.setId(Integer.parseInt(txtId.getText()));
    }

}
