/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.EntradaProdutoCTRL;
import controller.FornecedorCTRL;
import controller.InversorCTRL;
import controller.ItemEntradaCTRL;
import controller.ModuloCTRL;
import java.awt.HeadlessException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import model.bean.EntradaProduto;
import model.bean.Fornecedor;
import model.bean.Inversor;
import model.bean.ItemEntrada;
import model.bean.Modulo;
import utils.IconManager;
import utils.ManagerJasperReport;
import utils.Utilitarios;

/**
 *
 * @author KAI
 */
public class DlgEntradaProduto extends javax.swing.JDialog {

    private EntradaProduto pEntradaProduto;
    private boolean FirstRun = true;

    /**
     * Creates new form DlgEntradaProduto
     *
     * @param parent
     * @param modal
     */
    public DlgEntradaProduto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public DlgEntradaProduto(java.awt.Frame parent, boolean modal, EntradaProduto ep_) {
        super(parent, modal);
        initComponents();
        this.pEntradaProduto = ep_;
        this.IniciaForm();
        this.FirstRun = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlGeral = new javax.swing.JPanel();
        txtTotalLiquido = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtFornecedor = new javax.swing.JTextField();
        btnLocalizarFornecedor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtDescontos = new javax.swing.JFormattedTextField();
        txtTotalProdutos = new javax.swing.JFormattedTextField();
        txtData1 = new javax.swing.JTextField();
        pnlItens = new javax.swing.JPanel();
        pnlInversores = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblIEInversores = new javax.swing.JTable();
        btnInvsersorAdd = new javax.swing.JButton();
        btnInversorRem = new javax.swing.JButton();
        pnlModulos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblIEModulos = new javax.swing.JTable();
        btnModuloAdd = new javax.swing.JButton();
        btnModuloRem = new javax.swing.JButton();
        pnlBotoes = new javax.swing.JPanel();
        btnGravar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnFicha = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Entrada de Produtos");
        setResizable(false);

        pnlGeral.setBorder(javax.swing.BorderFactory.createTitledBorder("Geral"));

        txtTotalLiquido.setEditable(false);
        txtTotalLiquido.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        txtTotalLiquido.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtTotalLiquido.setEnabled(false);

        jLabel5.setText("Total Líquido:");

        jLabel6.setText("Fornecedor:");

        txtFornecedor.setEditable(false);
        txtFornecedor.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtFornecedor.setEnabled(false);
        txtFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFornecedorActionPerformed(evt);
            }
        });

        btnLocalizarFornecedor.setText("Buscar Fornecedor");
        btnLocalizarFornecedor.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnLocalizarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocalizarFornecedorActionPerformed(evt);
            }
        });

        jLabel1.setText("Id:");

        jLabel2.setText("Data:");

        jLabel3.setText("Descontos:");

        jLabel4.setText("Total Produtos:");

        txtId.setEditable(false);
        txtId.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtId.setEnabled(false);
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        txtDescontos.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        txtTotalProdutos.setEditable(false);
        txtTotalProdutos.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        txtTotalProdutos.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtTotalProdutos.setEnabled(false);

        txtData1.setEditable(false);
        txtData1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtData1.setEnabled(false);

        javax.swing.GroupLayout pnlGeralLayout = new javax.swing.GroupLayout(pnlGeral);
        pnlGeral.setLayout(pnlGeralLayout);
        pnlGeralLayout.setHorizontalGroup(
            pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGeralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlGeralLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFornecedor))
                    .addGroup(pnlGeralLayout.createSequentialGroup()
                        .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlGeralLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtData1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlGeralLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotalProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDescontos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnLocalizarFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(txtTotalLiquido))
                .addContainerGap())
        );

        pnlGeralLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel4, jLabel6});

        pnlGeralLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3});

        pnlGeralLayout.setVerticalGroup(
            pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGeralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtData1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLocalizarFornecedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTotalProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtDescontos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtTotalLiquido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlItens.setBorder(javax.swing.BorderFactory.createTitledBorder("Itens/Produtos"));

        pnlInversores.setBorder(javax.swing.BorderFactory.createTitledBorder("Inversores"));

        tblIEInversores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblIEInversores);

        btnInvsersorAdd.setText("Adicionar");
        btnInvsersorAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvsersorAddActionPerformed(evt);
            }
        });

        btnInversorRem.setText("Remover");
        btnInversorRem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInversorRemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlInversoresLayout = new javax.swing.GroupLayout(pnlInversores);
        pnlInversores.setLayout(pnlInversoresLayout);
        pnlInversoresLayout.setHorizontalGroup(
            pnlInversoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInversoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInversoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnInversorRem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(btnInvsersorAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        pnlInversoresLayout.setVerticalGroup(
            pnlInversoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInversoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInversoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInversoresLayout.createSequentialGroup()
                        .addComponent(btnInvsersorAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnInversorRem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 37, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlModulos.setBorder(javax.swing.BorderFactory.createTitledBorder("Módulos"));

        tblIEModulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblIEModulos);

        btnModuloAdd.setText("Adicionar");
        btnModuloAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModuloAddActionPerformed(evt);
            }
        });

        btnModuloRem.setText("Remover");
        btnModuloRem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModuloRemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlModulosLayout = new javax.swing.GroupLayout(pnlModulos);
        pnlModulos.setLayout(pnlModulosLayout);
        pnlModulosLayout.setHorizontalGroup(
            pnlModulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlModulosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlModulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnModuloAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModuloRem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        pnlModulosLayout.setVerticalGroup(
            pnlModulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlModulosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlModulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlModulosLayout.createSequentialGroup()
                        .addComponent(btnModuloAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnModuloRem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 37, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlItensLayout = new javax.swing.GroupLayout(pnlItens);
        pnlItens.setLayout(pnlItensLayout);
        pnlItensLayout.setHorizontalGroup(
            pnlItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlInversores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlModulos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlItensLayout.setVerticalGroup(
            pnlItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlItensLayout.createSequentialGroup()
                .addComponent(pnlInversores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlModulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlBotoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Ações"));

        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Fechar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnFicha.setText("Ficha");
        btnFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFichaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBotoesLayout = new javax.swing.GroupLayout(pnlBotoes);
        pnlBotoes.setLayout(pnlBotoesLayout);
        pnlBotoesLayout.setHorizontalGroup(
            pnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGravar, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(btnFicha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBotoesLayout.setVerticalGroup(
            pnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGravar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFicha)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlItens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlGeral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(pnlItens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFornecedorActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        this.GravarEntradaProdutos();
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnLocalizarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocalizarFornecedorActionPerformed
        DlgPesquisaEntidade dlg = new DlgPesquisaEntidade(null, true, Fornecedor.class, null, null, true);
        dlg.setVisible(true);
        dlg.toFront();
        int id = dlg.getIdSelecionado();
        if (id > 0) {
            this.pEntradaProduto.setFornecedor(FornecedorCTRL.BuscarPorId(dlg.getIdSelecionado()));
            txtFornecedor.setText(this.pEntradaProduto.getFornecedor().AsString());
        }
    }//GEN-LAST:event_btnLocalizarFornecedorActionPerformed

    private void btnInvsersorAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvsersorAddActionPerformed
        DlgPesquisaEntidade dlg = new DlgPesquisaEntidade(null, true, Inversor.class, null, null, true);
        dlg.setVisible(true);
        dlg.toFront();
        int id = dlg.getIdSelecionado();
        if (id > 0) {
            ItemEntrada ie = new ItemEntrada(0);
            ie.setQuantidade(0);
            ie.setValorUnitario(0);
            ie.setValorTotal_(0);
            ie.setEntradaProduto(this.pEntradaProduto);
            ie.setInversor(InversorCTRL.BuscaPorId(id));
            this.AtualizaItensEntradas(ie, null, -1, -1);
            this.PopulaJTableInvesores();
        }
    }//GEN-LAST:event_btnInvsersorAddActionPerformed

    private void btnModuloAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModuloAddActionPerformed
        DlgPesquisaEntidade dlg = new DlgPesquisaEntidade(null, true, Modulo.class, null, null, true);
        dlg.setVisible(true);
        dlg.toFront();
        int id = dlg.getIdSelecionado();
        if (id > 0) {
            ItemEntrada ie = new ItemEntrada(0);
            ie.setQuantidade(0);
            ie.setValorUnitario(0);
            ie.setValorTotal_(0);
            ie.setEntradaProduto(this.pEntradaProduto);
            ie.setModulo(ModuloCTRL.BuscaPorId(id));
            this.AtualizaItensEntradas(null, ie, -1, -1);
            this.PopulaJTableModulos();
        }
    }//GEN-LAST:event_btnModuloAddActionPerformed

    private void btnInversorRemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInversorRemActionPerformed
        try {
            int i = Integer.valueOf("" + tblIEInversores.getValueAt(tblIEInversores.getSelectedRow(), 0));
            if (JOptionPane.showConfirmDialog(null, "Deseja realmente Deletar este registro?", "<<< ATENÇÃO >>>", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
                this.AtualizaItensEntradas(null, null, i, -1);
                this.PopulaJTableInvesores();
            }
        } catch (HeadlessException | NumberFormatException e) {
            Utilitarios.MsgExcecao("Erro ao tentar buscar Excluir um Item de Entrada: " + e);
            Logger.getLogger(EntradaProduto.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btnInversorRemActionPerformed

    private void btnModuloRemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModuloRemActionPerformed
        try {
            int i = Integer.valueOf("" + tblIEModulos.getValueAt(tblIEModulos.getSelectedRow(), 0));
            if (JOptionPane.showConfirmDialog(null, "Deseja realmente Deletar este registro?", "<<< ATENÇÃO >>>", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
                this.AtualizaItensEntradas(null, null, -1, i);
                this.PopulaJTableModulos();
            }
        } catch (HeadlessException | NumberFormatException e) {
            Utilitarios.MsgExcecao("Erro ao tentar buscar Excluir um Item de Entrada: " + e);
            Logger.getLogger(EntradaProduto.class.getName()).log(Level.SEVERE, null, e);
        }

    }//GEN-LAST:event_btnModuloRemActionPerformed

    private void btnFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFichaActionPerformed
        Map params = new HashMap();
        params.put("idEP", this.pEntradaProduto.getId());
        new ManagerJasperReport().ExecutaRelatorio("EntradaProdutos", "Entrada de Produtos", params);
    }//GEN-LAST:event_btnFichaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgEntradaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            DlgEntradaProduto dialog = new DlgEntradaProduto(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnFicha;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnInversorRem;
    private javax.swing.JButton btnInvsersorAdd;
    private javax.swing.JButton btnLocalizarFornecedor;
    private javax.swing.JButton btnModuloAdd;
    private javax.swing.JButton btnModuloRem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlBotoes;
    private javax.swing.JPanel pnlGeral;
    private javax.swing.JPanel pnlInversores;
    private javax.swing.JPanel pnlItens;
    private javax.swing.JPanel pnlModulos;
    private javax.swing.JTable tblIEInversores;
    private javax.swing.JTable tblIEModulos;
    private javax.swing.JTextField txtData1;
    private javax.swing.JFormattedTextField txtDescontos;
    private javax.swing.JTextField txtFornecedor;
    private javax.swing.JTextField txtId;
    private javax.swing.JFormattedTextField txtTotalLiquido;
    private javax.swing.JFormattedTextField txtTotalProdutos;
    // End of variables declaration//GEN-END:variables

    private void IniciaForm() {
        this.PreencheCamposComObjetoEP();
        new IconManager().SetaIcones(new JButton[]{
            btnGravar, btnCancelar, btnLocalizarFornecedor,
            btnInvsersorAdd, btnInversorRem, btnModuloAdd, btnModuloRem
        });

        for (JButton b_ : new JButton[]{btnInvsersorAdd, btnInversorRem, btnModuloAdd, btnModuloRem}) {
            b_.setText("");
        }
    }

    private void PreencheCamposComObjetoEP() {
        txtData1.setText(Utilitarios.ConverteDataParaString(this.pEntradaProduto.getData(), ""));
        txtDescontos.setText(String.valueOf(this.pEntradaProduto.getDescontos()).replace(",", "").replace(".", ","));
        txtTotalLiquido.setText(String.valueOf(this.pEntradaProduto.getValorLiquido_()).replace(",", "").replace(".", ","));
        txtTotalProdutos.setText(String.valueOf(this.pEntradaProduto.getValorProdutos_()).replace(",", "").replace(".", ","));
        txtFornecedor.setText(
                this.pEntradaProduto.getFornecedor() != null
                ? this.pEntradaProduto.getFornecedor().AsString() : ""
        );
        txtId.setText(String.valueOf(this.pEntradaProduto.getId()));

        this.PopulaJTableInvesores();
        this.PopulaJTableModulos();
    }

    private void GravarEntradaProdutos() {
        this.PreencheObjetoEP_ComCampos();

        this.AtualizaItensEntradas(null, null, -1, -1);

        this.pEntradaProduto = EntradaProdutoCTRL.Gravar(this.pEntradaProduto);
        this.PreencheCamposComObjetoEP();
    }

    private void PreencheObjetoEP_ComCampos() {
        this.pEntradaProduto.setDescontos(Utilitarios.ConverteTextoEmDouble(txtDescontos.getText()));
    }

    private void PopulaJTableInvesores() {
        List<ItemEntrada> itens = new ArrayList<>();
        if (this.pEntradaProduto.getItens() != null) {
            for (ItemEntrada item : this.pEntradaProduto.getItens()) {
                if (item.getInversor() != null) {
                    itens.add(item);
                }
            }
        }

        String[] colunas = "Id,Id.I,Modelo,Valor,Quantidade,Total".split(",");

        Object[][] dados = new Object[itens.size()][colunas.length];
        for (int linha = 0; linha < itens.size(); linha++) {
            int coluna = 0;
            dados[linha][coluna++] = itens.get(linha).getId();
            dados[linha][coluna++] = itens.get(linha).getInversor().getId();
            dados[linha][coluna++] = itens.get(linha).getInversor().getModelo();
            dados[linha][coluna++] = String.valueOf(itens.get(linha).getValorUnitario()).replace(",", "").replace(".", ",");
            dados[linha][coluna++] = itens.get(linha).getQuantidade();
            dados[linha][coluna++] = String.valueOf(itens.get(linha).getValorUnitario() * itens.get(linha).getQuantidade()).replace(",", "").replace(".", ",");
        }
        DefaultTableModel mdl = new DefaultTableModel(dados, colunas) {
            boolean[] canEdit = new boolean[]{
                false, false, false, true, true, false
            };

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };
        tblIEInversores.setModel(mdl);
        tblIEInversores.setAutoCreateRowSorter(true);
        tblIEInversores.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tblIEInversores.setShowGrid(true);
        tblIEInversores.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        int xx = 0;
        tblIEInversores.getColumnModel().getColumn(xx++).setPreferredWidth((int) (tblIEInversores.getParent().getWidth() * 0.05));
        tblIEInversores.getColumnModel().getColumn(xx++).setPreferredWidth((int) (tblIEInversores.getParent().getWidth() * 0.05));
        tblIEInversores.getColumnModel().getColumn(xx++).setPreferredWidth((int) (tblIEInversores.getParent().getWidth() * 0.50));
        tblIEInversores.getColumnModel().getColumn(xx++).setPreferredWidth((int) (tblIEInversores.getParent().getWidth() * 0.15));
        tblIEInversores.getColumnModel().getColumn(xx++).setPreferredWidth((int) (tblIEInversores.getParent().getWidth() * 0.10));
        tblIEInversores.getColumnModel().getColumn(xx++).setPreferredWidth((int) (tblIEInversores.getParent().getWidth() * 0.15));
    }

    private void PopulaJTableModulos() {
        List<ItemEntrada> itens = new ArrayList<>();

        if (this.pEntradaProduto.getItens() != null) {
            for (ItemEntrada item : this.pEntradaProduto.getItens()) {
                if (item.getModulo() != null) {
                    itens.add(item);
                }
            }
        }

        String[] colunas = "Id,Id.M,Modelo,Valor,Quantidade,Total".split(",");

        Object[][] dados = new Object[itens.size()][colunas.length];
        for (int linha = 0; linha < itens.size(); linha++) {
            int coluna = 0;
            dados[linha][coluna++] = itens.get(linha).getId();
            dados[linha][coluna++] = itens.get(linha).getModulo().getId();
            dados[linha][coluna++] = itens.get(linha).getModulo().getModelo();
            dados[linha][coluna++] = String.valueOf(itens.get(linha).getValorUnitario()).replace(",", "").replace(".", ",");
            dados[linha][coluna++] = itens.get(linha).getQuantidade();
            dados[linha][coluna++] = String.valueOf(itens.get(linha).getValorUnitario() * itens.get(linha).getQuantidade()).replace(",", "").replace(".", ",");
        }
//        Class[] tpClass = new Class[]{
//            Integer.class,
//            Integer.class,
//            String.class,
//            Double.class,
//            Integer.class,
//            Double.class
//        };
        DefaultTableModel mdl = new DefaultTableModel(dados, colunas) {
            boolean[] canEdit = new boolean[]{
                false, false, false, true, true, false
            };

//            @Override
//            public Class getColumnClass(int columnIndex) {
//                return tpClass[columnIndex];
//            }
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };
        tblIEModulos.setModel(mdl);
        tblIEModulos.setAutoCreateRowSorter(true);
        tblIEModulos.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tblIEModulos.setShowGrid(true);
        tblIEModulos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        javax.swing.JFormattedTextField txtDouble = new javax.swing.JFormattedTextField();
        txtDouble.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));

        javax.swing.JFormattedTextField txtInteiro = new javax.swing.JFormattedTextField();
        txtInteiro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        int xx = 0;
        tblIEModulos.getColumnModel().getColumn(xx++).setPreferredWidth((int) (tblIEModulos.getParent().getWidth() * 0.05));
        tblIEModulos.getColumnModel().getColumn(xx++).setPreferredWidth((int) (tblIEModulos.getParent().getWidth() * 0.05));
        tblIEModulos.getColumnModel().getColumn(xx++).setPreferredWidth((int) (tblIEModulos.getParent().getWidth() * 0.50));
        tblIEModulos.getColumnModel().getColumn(3).setCellEditor(new DefaultCellEditor(txtDouble));
        tblIEModulos.getColumnModel().getColumn(xx++).setPreferredWidth((int) (tblIEModulos.getParent().getWidth() * 0.15));
        tblIEModulos.getColumnModel().getColumn(4).setCellEditor(new DefaultCellEditor(txtInteiro));
        tblIEModulos.getColumnModel().getColumn(xx++).setPreferredWidth((int) (tblIEModulos.getParent().getWidth() * 0.10));
        tblIEModulos.getColumnModel().getColumn(5).setCellEditor(new DefaultCellEditor(txtDouble));
        tblIEModulos.getColumnModel().getColumn(xx++).setPreferredWidth((int) (tblIEModulos.getParent().getWidth() * 0.15));
    }

    private void AtualizaItensEntradas(ItemEntrada NewIE_Inversor, ItemEntrada NewIE_Modulo, int IdInversorExcluir, int IdModuloExcluir) {
        List<ItemEntrada> itens = new ArrayList<>();

        for (int i = 0; i < tblIEInversores.getRowCount(); i++) {
            ItemEntrada item = new ItemEntrada();
            item.setEntradaProduto(this.pEntradaProduto);
            item.setId(Integer.valueOf("" + tblIEInversores.getValueAt(i, 0)));
            item.setInversor(InversorCTRL.BuscaPorId(Integer.valueOf("" + tblIEInversores.getValueAt(i, 1))));
            item.setValorUnitario(Utilitarios.ConverteTextoEmDouble("" + tblIEInversores.getValueAt(i, 3)));
            item.setQuantidade(Utilitarios.ConverteTextoEmInteiro("" + tblIEInversores.getValueAt(i, 4)));

            if (IdInversorExcluir > -1) {
                if (IdInversorExcluir == item.getId() /*&& item.getId() > 0*/) {
                    ItemEntradaCTRL.Deletar(IdInversorExcluir);
                } else {
                    itens.add(item);
                }
            } else {
                itens.add(item);
            }
        }

        for (int i = 0; i < tblIEModulos.getRowCount(); i++) {
            ItemEntrada item = new ItemEntrada();
            item.setEntradaProduto(this.pEntradaProduto);
            item.setId(Integer.valueOf("" + tblIEModulos.getValueAt(i, 0)));
            item.setModulo(ModuloCTRL.BuscaPorId(Integer.valueOf("" + tblIEModulos.getValueAt(i, 1))));
            item.setValorUnitario(Utilitarios.ConverteTextoEmDouble("" + tblIEModulos.getValueAt(i, 3)));
            item.setQuantidade(Utilitarios.ConverteTextoEmInteiro("" + tblIEModulos.getValueAt(i, 4)));

            if (IdModuloExcluir > -1) {
                if (IdModuloExcluir == item.getId() /*&& item.getId() > 0*/) {
                    ItemEntradaCTRL.Deletar(IdModuloExcluir);
                } else {
                    itens.add(item);
                }
            } else {
                itens.add(item);
            }
        }

        if (NewIE_Inversor != null) {
            itens.add(NewIE_Inversor);
        }
        if (NewIE_Modulo != null) {
            itens.add(NewIE_Modulo);
        }

        this.pEntradaProduto.setItens(itens);
    }
}
