package view;

import connection.DataConnection;
import controller.UsuarioCTRL;
import java.awt.Frame;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import model.bean.Cliente;
import model.bean.EntradaProduto;
import model.bean.Fornecedor;
import model.bean.Inversor;
import model.bean.IrradiacaoGlobalMes;
import model.bean.Modulo;
import model.bean.Projeto;
import model.bean.Usuario;
import utils.ManagerJasperReport;
import utils.Utilitarios;

/**
 *
 * @author KAI
 */
public final class FrmMain extends javax.swing.JFrame {

    private Usuario usuario;

    /**
     * Creates new form FrmMain
     *
     * @param pUsuario
     */
    public FrmMain(Usuario pUsuario) {
        initComponents();
        this.setUsuario(pUsuario);
        this.setIconImage(new ImageIcon(getClass().getResource("/image/solar-panel1.png")).getImage());
        this.setIconsMenus();
        this.HabilitaMenusItensDeAcordoComPerfilDoUsuario();
    }

    private FrmMain() {
        initComponents();
    }

    public Usuario getUsuario() {
        return usuario;
    }

    public void setUsuario(Usuario pUser) {
        this.usuario = pUser;
        lblUsuarioLogado.setText(pUser.getNome().concat(" | ").concat(pUser.getPerfilGrupo().toString()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBotton = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblUsuarioLogado = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mbMain = new javax.swing.JMenuBar();
        mnCadastros = new javax.swing.JMenu();
        mnModulos = new javax.swing.JMenu();
        miModuloNovo = new javax.swing.JMenuItem();
        miModuloPesquisar = new javax.swing.JMenuItem();
        mnInversores = new javax.swing.JMenu();
        miInversorNovo = new javax.swing.JMenuItem();
        miInversorPesquisar = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnFornecedor = new javax.swing.JMenu();
        miFornecedorNovo = new javax.swing.JMenuItem();
        miFornecedorPesquisar = new javax.swing.JMenuItem();
        mnEntradaProduto = new javax.swing.JMenu();
        miEPNovo = new javax.swing.JMenuItem();
        miEPPesquisar = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnCliente = new javax.swing.JMenu();
        miNovoCliente = new javax.swing.JMenuItem();
        miPesquisarCliente = new javax.swing.JMenuItem();
        mnProjetoFotovoltaico = new javax.swing.JMenu();
        miProjetoNovo = new javax.swing.JMenuItem();
        miProjetoPesquisar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnIrradiacaoGlobal = new javax.swing.JMenu();
        miIrradiacaoGlobalMesNovo = new javax.swing.JMenuItem();
        miIrradiacaoGlobalMesPesquisar = new javax.swing.JMenuItem();
        mnUsuario = new javax.swing.JMenu();
        miUsuarioNovo = new javax.swing.JMenuItem();
        miUsuarioPesquisar = new javax.swing.JMenuItem();
        mnRelatorios = new javax.swing.JMenu();
        miListagemDeProjetos = new javax.swing.JMenuItem();
        miListagemDeModulos = new javax.swing.JMenuItem();
        miListagemDeInversores = new javax.swing.JMenuItem();
        miSaldoEstoque = new javax.swing.JMenuItem();
        miListagemDeUsuarios = new javax.swing.JMenuItem();
        mnAlterarCredenciaisUsuario = new javax.swing.JMenu();
        miAlterarCredenciaisUsuario = new javax.swing.JMenuItem();
        miFazerLogoff = new javax.swing.JMenuItem();
        mnFecharSistema = new javax.swing.JMenu();
        miSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("iRRadiação Solarimétrica");

        pnlBotton.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Usuário:");

        lblUsuarioLogado.setText("UsuárioLogado");

        javax.swing.GroupLayout pnlBottonLayout = new javax.swing.GroupLayout(pnlBotton);
        pnlBotton.setLayout(pnlBottonLayout);
        pnlBottonLayout.setHorizontalGroup(
            pnlBottonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBottonLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsuarioLogado)
                .addGap(0, 511, Short.MAX_VALUE))
        );
        pnlBottonLayout.setVerticalGroup(
            pnlBottonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBottonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(lblUsuarioLogado))
        );

        jLabel2.setBackground(new java.awt.Color(240, 248, 247));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fundo transparente.png"))); // NOI18N

        mnCadastros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/file.png"))); // NOI18N
        mnCadastros.setText("Cadastros");

        mnModulos.setText("Módulos");

        miModuloNovo.setText("Novo");
        miModuloNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miModuloNovoActionPerformed(evt);
            }
        });
        mnModulos.add(miModuloNovo);

        miModuloPesquisar.setText("Pesquisar");
        miModuloPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miModuloPesquisarActionPerformed(evt);
            }
        });
        mnModulos.add(miModuloPesquisar);

        mnCadastros.add(mnModulos);

        mnInversores.setText("Inversores");

        miInversorNovo.setText("Novo");
        miInversorNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miInversorNovoActionPerformed(evt);
            }
        });
        mnInversores.add(miInversorNovo);

        miInversorPesquisar.setText("Pesquisar");
        miInversorPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miInversorPesquisarActionPerformed(evt);
            }
        });
        mnInversores.add(miInversorPesquisar);

        mnCadastros.add(mnInversores);
        mnCadastros.add(jSeparator2);

        mnFornecedor.setText("Fornecedor");

        miFornecedorNovo.setText("Novo");
        miFornecedorNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miFornecedorNovoActionPerformed(evt);
            }
        });
        mnFornecedor.add(miFornecedorNovo);

        miFornecedorPesquisar.setText("Pesquisar");
        miFornecedorPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miFornecedorPesquisarActionPerformed(evt);
            }
        });
        mnFornecedor.add(miFornecedorPesquisar);

        mnCadastros.add(mnFornecedor);

        mnEntradaProduto.setText("Entrada Produtos");

        miEPNovo.setText("Novo");
        miEPNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEPNovoActionPerformed(evt);
            }
        });
        mnEntradaProduto.add(miEPNovo);

        miEPPesquisar.setText("Pesquisar");
        miEPPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEPPesquisarActionPerformed(evt);
            }
        });
        mnEntradaProduto.add(miEPPesquisar);

        mnCadastros.add(mnEntradaProduto);
        mnCadastros.add(jSeparator3);

        mnCliente.setText("Cliente");

        miNovoCliente.setText("Novo");
        miNovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNovoClienteActionPerformed(evt);
            }
        });
        mnCliente.add(miNovoCliente);

        miPesquisarCliente.setText("Pesquisar");
        miPesquisarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPesquisarClienteActionPerformed(evt);
            }
        });
        mnCliente.add(miPesquisarCliente);

        mnCadastros.add(mnCliente);

        mnProjetoFotovoltaico.setText("Projeto Fotovoltáico");

        miProjetoNovo.setText("Novo");
        miProjetoNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miProjetoNovoActionPerformed(evt);
            }
        });
        mnProjetoFotovoltaico.add(miProjetoNovo);

        miProjetoPesquisar.setText("Pesquisar");
        miProjetoPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miProjetoPesquisarActionPerformed(evt);
            }
        });
        mnProjetoFotovoltaico.add(miProjetoPesquisar);

        mnCadastros.add(mnProjetoFotovoltaico);
        mnCadastros.add(jSeparator1);

        mnIrradiacaoGlobal.setText("Irradiações Globais");

        miIrradiacaoGlobalMesNovo.setText("Novo");
        miIrradiacaoGlobalMesNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miIrradiacaoGlobalMesNovoActionPerformed(evt);
            }
        });
        mnIrradiacaoGlobal.add(miIrradiacaoGlobalMesNovo);

        miIrradiacaoGlobalMesPesquisar.setText("Pesquisar");
        miIrradiacaoGlobalMesPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miIrradiacaoGlobalMesPesquisarActionPerformed(evt);
            }
        });
        mnIrradiacaoGlobal.add(miIrradiacaoGlobalMesPesquisar);

        mnCadastros.add(mnIrradiacaoGlobal);

        mnUsuario.setText("Usuário");

        miUsuarioNovo.setText("Novo");
        miUsuarioNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUsuarioNovoActionPerformed(evt);
            }
        });
        mnUsuario.add(miUsuarioNovo);

        miUsuarioPesquisar.setText("Pesquisar");
        miUsuarioPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUsuarioPesquisarActionPerformed(evt);
            }
        });
        mnUsuario.add(miUsuarioPesquisar);

        mnCadastros.add(mnUsuario);

        mbMain.add(mnCadastros);

        mnRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/report.png"))); // NOI18N
        mnRelatorios.setText("Relatório");

        miListagemDeProjetos.setText("Listagem de Projetos");
        miListagemDeProjetos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miListagemDeProjetosActionPerformed(evt);
            }
        });
        mnRelatorios.add(miListagemDeProjetos);

        miListagemDeModulos.setText("Listagem de Módulos");
        miListagemDeModulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miListagemDeModulosActionPerformed(evt);
            }
        });
        mnRelatorios.add(miListagemDeModulos);

        miListagemDeInversores.setText("Listagem de Inversores");
        miListagemDeInversores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miListagemDeInversoresActionPerformed(evt);
            }
        });
        mnRelatorios.add(miListagemDeInversores);

        miSaldoEstoque.setText("Saldo de Estoque");
        miSaldoEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSaldoEstoqueActionPerformed(evt);
            }
        });
        mnRelatorios.add(miSaldoEstoque);

        miListagemDeUsuarios.setText("Listagem de Usuários");
        miListagemDeUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miListagemDeUsuariosActionPerformed(evt);
            }
        });
        mnRelatorios.add(miListagemDeUsuarios);

        mbMain.add(mnRelatorios);

        mnAlterarCredenciaisUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user.png"))); // NOI18N
        mnAlterarCredenciaisUsuario.setText("Usuário");

        miAlterarCredenciaisUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ícones/Vcard.18px.png"))); // NOI18N
        miAlterarCredenciaisUsuario.setText("Alterar senha/login");
        miAlterarCredenciaisUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAlterarCredenciaisUsuarioActionPerformed(evt);
            }
        });
        mnAlterarCredenciaisUsuario.add(miAlterarCredenciaisUsuario);

        miFazerLogoff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ícones/user_go.png"))); // NOI18N
        miFazerLogoff.setText("Fazer Logoff");
        miFazerLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miFazerLogoffActionPerformed(evt);
            }
        });
        mnAlterarCredenciaisUsuario.add(miFazerLogoff);

        mbMain.add(mnAlterarCredenciaisUsuario);

        mnFecharSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout.png"))); // NOI18N
        mnFecharSistema.setText("Fechar o Sistema");

        miSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ícones/Shutdown_button.svg.16x16.png"))); // NOI18N
        miSair.setText("Sair");
        miSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSairActionPerformed(evt);
            }
        });
        mnFecharSistema.add(miSair);

        mbMain.add(mnFecharSistema);

        setJMenuBar(mbMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBotton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlBotton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSairActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Deseja realmente sair do sistema?", "Finalizar sistema?", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_miSairActionPerformed

    private void miAlterarCredenciaisUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAlterarCredenciaisUsuarioActionPerformed
        DlgUsuarioManager dlg = new DlgUsuarioManager(this, true, this.usuario);
        dlg.setVisible(true);
        dlg.toFront();
    }//GEN-LAST:event_miAlterarCredenciaisUsuarioActionPerformed

    private void miModuloNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miModuloNovoActionPerformed
        DlgModuloNEW dlg = new DlgModuloNEW(this, true, new Modulo(0));
        dlg.setVisible(true);
        dlg.toFront();
    }//GEN-LAST:event_miModuloNovoActionPerformed

    private void miInversorNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miInversorNovoActionPerformed
        DlgInversorNEW dlg = new DlgInversorNEW(this, true, new Inversor(0));
        dlg.setVisible(true);
        dlg.toFront();
    }//GEN-LAST:event_miInversorNovoActionPerformed

    private void miIrradiacaoGlobalMesNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miIrradiacaoGlobalMesNovoActionPerformed
        DlgIrradiacaoGlobalMesNEW dlg = new DlgIrradiacaoGlobalMesNEW(this, true, new IrradiacaoGlobalMes(0));
        dlg.setVisible(true);
        dlg.toFront();
    }//GEN-LAST:event_miIrradiacaoGlobalMesNovoActionPerformed

    private void miProjetoNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miProjetoNovoActionPerformed
        DlgProjetoNew dlg = new DlgProjetoNew(this, true, new Projeto());
        dlg.setVisible(true);
        dlg.toFront();
    }//GEN-LAST:event_miProjetoNovoActionPerformed

    private void miProjetoPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miProjetoPesquisarActionPerformed
        DlgPesquisaEntidade dlg = new DlgPesquisaEntidade(this, true,
                Projeto.class,
                new String[]{"Cliente", "Id"},
                new String[]{"Id", "Cliente", "Data Criação", "Status"},
                false
        );
        dlg.setVisible(true);
        dlg.toFront();
    }//GEN-LAST:event_miProjetoPesquisarActionPerformed

    private void miListagemDeProjetosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miListagemDeProjetosActionPerformed
        try {
            Connection con = DataConnection.getConnection();
            new ManagerJasperReport().ExecutaRelatorio("EspelhoProjeto", "Projeto", null, con);
        } catch (SQLException ex) {
            System.out.println("?Error ao tentar emitir relatório: " + ex);
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_miListagemDeProjetosActionPerformed

    private void miNovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNovoClienteActionPerformed
        DlgClienteNEW1 dlg = new DlgClienteNEW1(null, true, new Cliente(0));
        dlg.setVisible(true);
        dlg.toFront();
    }//GEN-LAST:event_miNovoClienteActionPerformed

    private void miPesquisarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPesquisarClienteActionPerformed
        DlgPesquisaEntidade dlg = new DlgPesquisaEntidade(null, true, Cliente.class, null, null, false);
        dlg.setVisible(true);
        dlg.toFront();
    }//GEN-LAST:event_miPesquisarClienteActionPerformed

    private void miModuloPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miModuloPesquisarActionPerformed
        DlgPesquisaEntidade dlg = new DlgPesquisaEntidade(null, true, Modulo.class, null, null, false);
        dlg.setVisible(true);
        dlg.toFront();
    }//GEN-LAST:event_miModuloPesquisarActionPerformed

    private void miInversorPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miInversorPesquisarActionPerformed
        DlgPesquisaEntidade dlg = new DlgPesquisaEntidade(null, true, Inversor.class, null, null, false);
        dlg.setVisible(true);
        dlg.toFront();
    }//GEN-LAST:event_miInversorPesquisarActionPerformed

    private void miIrradiacaoGlobalMesPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miIrradiacaoGlobalMesPesquisarActionPerformed
        DlgPesquisaEntidade dlg = new DlgPesquisaEntidade(null, true, IrradiacaoGlobalMes.class, null, null, false);
        dlg.setVisible(true);
        dlg.toFront();
    }//GEN-LAST:event_miIrradiacaoGlobalMesPesquisarActionPerformed

    private void miUsuarioNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUsuarioNovoActionPerformed
        DlgUsuarioNEW dlg = new DlgUsuarioNEW(null, true, new Usuario(0));
        dlg.setVisible(true);
        dlg.toFront();
    }//GEN-LAST:event_miUsuarioNovoActionPerformed

    private void miUsuarioPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUsuarioPesquisarActionPerformed
        DlgPesquisaEntidade dlg = new DlgPesquisaEntidade(null, true, Usuario.class, null, null, false);
        dlg.setVisible(true);
        dlg.toFront();
    }//GEN-LAST:event_miUsuarioPesquisarActionPerformed

    private void miFazerLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miFazerLogoffActionPerformed
        this.setVisible(false);
        DlgLogin dlgLogin = new DlgLogin(null, true);
        dlgLogin.setVisible(true);
        dlgLogin.toFront();
        if (dlgLogin.usuario.getId() > 0) {

            this.setUsuario(UsuarioCTRL.BuscarPorId(dlgLogin.usuario.getId()));
            this.setIconImage(new ImageIcon(getClass().getResource("/image/solar-panel1.png")).getImage());
            this.setIconsMenus();
            this.HabilitaMenusItensDeAcordoComPerfilDoUsuario();

//            FrmMain frmMain = new FrmMain(dlgLogin.usuario);
            this.setVisible(true);
            this.setExtendedState(Frame.MAXIMIZED_BOTH);
            this.toFront();
        } else {
            System.exit(0);
        }

    }//GEN-LAST:event_miFazerLogoffActionPerformed

    private void miListagemDeModulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miListagemDeModulosActionPerformed
        try {
            Connection con = DataConnection.getConnection();
            new ManagerJasperReport().ExecutaRelatorio("ListagemDeModulos", "Listatem de Módulos", null, con);
        } catch (SQLException ex) {
            System.out.println("?Error ao tentar emitir relatório: " + ex);
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_miListagemDeModulosActionPerformed

    private void miListagemDeInversoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miListagemDeInversoresActionPerformed
        try {
            Connection con = DataConnection.getConnection();
            new ManagerJasperReport().ExecutaRelatorio("ListagemDeInversores", "Listagem de Inversores", null, con);
        } catch (SQLException ex) {
            System.out.println("?Error ao tentar emitir relatório: " + ex);
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_miListagemDeInversoresActionPerformed

    private void miFornecedorNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miFornecedorNovoActionPerformed
        DlgFornecedor dlg = new DlgFornecedor(null, true, new Fornecedor(0));
        dlg.setVisible(true);
        dlg.toFront();
    }//GEN-LAST:event_miFornecedorNovoActionPerformed

    private void miFornecedorPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miFornecedorPesquisarActionPerformed
        DlgPesquisaEntidade dlg = new DlgPesquisaEntidade(null, true, Fornecedor.class, null, null, false);
        dlg.setVisible(true);
        dlg.toFront();
    }//GEN-LAST:event_miFornecedorPesquisarActionPerformed

    private void miEPNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEPNovoActionPerformed
        DlgEntradaProduto dlg = new DlgEntradaProduto(null, true, new EntradaProduto(0));
        dlg.setVisible(true);
        dlg.toFront();

    }//GEN-LAST:event_miEPNovoActionPerformed

    private void miEPPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEPPesquisarActionPerformed
        DlgPesquisaEntidade dlg = new DlgPesquisaEntidade(null, true, EntradaProduto.class, null, null, false);
        dlg.setVisible(true);
        dlg.toFront();
    }//GEN-LAST:event_miEPPesquisarActionPerformed

    private void miSaldoEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSaldoEstoqueActionPerformed
        new ManagerJasperReport().ExecutaRelatorio("SaldoProdutos", "Saldo de Estoque", null);
    }//GEN-LAST:event_miSaldoEstoqueActionPerformed

    private void miListagemDeUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miListagemDeUsuariosActionPerformed
        new ManagerJasperReport().ExecutaRelatorio("ListagemDeUsuarios", "Listagem de Usuários", null);
    }//GEN-LAST:event_miListagemDeUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrmMain().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JLabel lblUsuarioLogado;
    private javax.swing.JMenuBar mbMain;
    private javax.swing.JMenuItem miAlterarCredenciaisUsuario;
    private javax.swing.JMenuItem miEPNovo;
    private javax.swing.JMenuItem miEPPesquisar;
    private javax.swing.JMenuItem miFazerLogoff;
    private javax.swing.JMenuItem miFornecedorNovo;
    private javax.swing.JMenuItem miFornecedorPesquisar;
    private javax.swing.JMenuItem miInversorNovo;
    private javax.swing.JMenuItem miInversorPesquisar;
    private javax.swing.JMenuItem miIrradiacaoGlobalMesNovo;
    private javax.swing.JMenuItem miIrradiacaoGlobalMesPesquisar;
    private javax.swing.JMenuItem miListagemDeInversores;
    private javax.swing.JMenuItem miListagemDeModulos;
    private javax.swing.JMenuItem miListagemDeProjetos;
    private javax.swing.JMenuItem miListagemDeUsuarios;
    private javax.swing.JMenuItem miModuloNovo;
    private javax.swing.JMenuItem miModuloPesquisar;
    private javax.swing.JMenuItem miNovoCliente;
    private javax.swing.JMenuItem miPesquisarCliente;
    private javax.swing.JMenuItem miProjetoNovo;
    private javax.swing.JMenuItem miProjetoPesquisar;
    private javax.swing.JMenuItem miSair;
    private javax.swing.JMenuItem miSaldoEstoque;
    private javax.swing.JMenuItem miUsuarioNovo;
    private javax.swing.JMenuItem miUsuarioPesquisar;
    private javax.swing.JMenu mnAlterarCredenciaisUsuario;
    private javax.swing.JMenu mnCadastros;
    private javax.swing.JMenu mnCliente;
    private javax.swing.JMenu mnEntradaProduto;
    private javax.swing.JMenu mnFecharSistema;
    private javax.swing.JMenu mnFornecedor;
    private javax.swing.JMenu mnInversores;
    private javax.swing.JMenu mnIrradiacaoGlobal;
    private javax.swing.JMenu mnModulos;
    private javax.swing.JMenu mnProjetoFotovoltaico;
    private javax.swing.JMenu mnRelatorios;
    private javax.swing.JMenu mnUsuario;
    private javax.swing.JPanel pnlBotton;
    // End of variables declaration//GEN-END:variables

    private void setIconsMenus() {
        ImageIcon iconNew = new javax.swing.ImageIcon(getClass().getResource("/image/novo.png"));
        ImageIcon iconSearch = new javax.swing.ImageIcon(getClass().getResource("/image/procurar.19px.png"));

        JMenuItem[] miNew = new JMenuItem[]{miModuloNovo, miIrradiacaoGlobalMesNovo, miInversorNovo,
            miProjetoNovo, miUsuarioNovo, miNovoCliente, miFornecedorNovo, miEPNovo};
        for (JMenuItem mi : miNew) {
            mi.setIcon(iconNew);
            mi.setMnemonic(KeyEvent.VK_N);
        }

        JMenuItem[] miSearch = new JMenuItem[]{miModuloPesquisar, miIrradiacaoGlobalMesPesquisar, miInversorPesquisar,
            miProjetoPesquisar, miUsuarioPesquisar, miPesquisarCliente, miFornecedorPesquisar, miEPPesquisar};
        for (JMenuItem mi : miSearch) {
            mi.setIcon(iconSearch);
            mi.setMnemonic(KeyEvent.VK_P);
        }
    }

    private void HabilitaMenusItensDeAcordoComPerfilDoUsuario() {
        Utilitarios u_ = new Utilitarios();

        Usuario.PerfilGrupo A = Usuario.PerfilGrupo.Administrador;
        Usuario.PerfilGrupo E = Usuario.PerfilGrupo.Engenheiro;
        Usuario.PerfilGrupo V = Usuario.PerfilGrupo.Vendedor;

        mnCadastros.setMnemonic(KeyEvent.VK_C);
        mnCadastros.setEnabled(u_.HabilitaJMenu(Usuario.PerfilGrupo.values(), this.getUsuario().getPerfilGrupo(), mnCadastros));
        //<editor-fold defaultstate="collapsed" desc="Submenús Módulos">
        mnModulos.setMnemonic(KeyEvent.VK_M);
        mnModulos.setEnabled(u_.HabilitaJMenu(new Usuario.PerfilGrupo[]{A, E}, this.getUsuario().getPerfilGrupo(), mnCadastros));
//        miModuloNovo.setEnabled(u_.HabilitaJMenu(new Usuario.PerfilGrupo[]{A, E, V}, this.getUsuario().getPerfilGrupo(), mnCadastros));
//        miModuloPesquisar.setEnabled(u_.HabilitaJMenu(new Usuario.PerfilGrupo[]{A, E, V}, this.getUsuario().getPerfilGrupo(), mnCadastros));
        //</editor-fold>

        //<editor-fold defaultstate="collapsed" desc="Submenús Inversores">
        mnInversores.setMnemonic(KeyEvent.VK_V);
        mnInversores.setEnabled(u_.HabilitaJMenu(new Usuario.PerfilGrupo[]{A, E}, this.getUsuario().getPerfilGrupo(), mnCadastros));
//        miInversorNovo.setEnabled(u_.HabilitaJMenu(new Usuario.PerfilGrupo[]{A, E, V}, this.getUsuario().getPerfilGrupo(), mnCadastros));
//        miInversorPesquisar.setEnabled(u_.HabilitaJMenu(new Usuario.PerfilGrupo[]{A, E, V}, this.getUsuario().getPerfilGrupo(), mnCadastros));
        //</editor-fold>

        //<editor-fold defaultstate="collapsed" desc="Submenús Fornecedores">
        mnFornecedor.setMnemonic(KeyEvent.VK_D);
        mnFornecedor.setEnabled(u_.HabilitaJMenu(new Usuario.PerfilGrupo[]{A, V}, this.getUsuario().getPerfilGrupo(), mnCadastros));
//        miFornecedorNovo.setEnabled(u_.HabilitaJMenu(new Usuario.PerfilGrupo[]{A, E, V}, this.getUsuario().getPerfilGrupo(), mnCadastros));
//        miFornecedorPesquisar.setEnabled(u_.HabilitaJMenu(new Usuario.PerfilGrupo[]{A, E, V}, this.getUsuario().getPerfilGrupo(), mnCadastros));
        //</editor-fold>

        //<editor-fold defaultstate="collapsed" desc="Submenús Entrada de Produtos">
        mnEntradaProduto.setMnemonic(KeyEvent.VK_T);
        mnEntradaProduto.setEnabled(u_.HabilitaJMenu(new Usuario.PerfilGrupo[]{A, V}, this.getUsuario().getPerfilGrupo(), mnCadastros));
//        miEPNovo.setEnabled(u_.HabilitaJMenu(new Usuario.PerfilGrupo[]{A, E, V}, this.getUsuario().getPerfilGrupo(), mnCadastros));
//        miEPPesquisar.setEnabled(u_.HabilitaJMenu(new Usuario.PerfilGrupo[]{A, E, V}, this.getUsuario().getPerfilGrupo(), mnCadastros));
        //</editor-fold>

        //<editor-fold defaultstate="collapsed" desc="Submenús Clientes">
        mnCliente.setMnemonic(KeyEvent.VK_E);
        mnCliente.setEnabled(u_.HabilitaJMenu(new Usuario.PerfilGrupo[]{A, E, V}, this.getUsuario().getPerfilGrupo(), mnCadastros));
//        miNovoCliente.setEnabled(u_.HabilitaJMenu(new Usuario.PerfilGrupo[]{A, E, V}, this.getUsuario().getPerfilGrupo(), mnCadastros));
//        miPesquisarCliente.setEnabled(u_.HabilitaJMenu(new Usuario.PerfilGrupo[]{A, E, V}, this.getUsuario().getPerfilGrupo(), mnCadastros));
        //</editor-fold>

        //<editor-fold defaultstate="collapsed" desc="Submenús Projetos">
        mnProjetoFotovoltaico.setMnemonic(KeyEvent.VK_J);
        mnProjetoFotovoltaico.setEnabled(u_.HabilitaJMenu(new Usuario.PerfilGrupo[]{A, E, V}, this.getUsuario().getPerfilGrupo(), mnCadastros));
//        miProjetoNovo.setEnabled(u_.HabilitaJMenu(new Usuario.PerfilGrupo[]{A, E, V}, this.getUsuario().getPerfilGrupo(), mnCadastros));
//        miProjetoPesquisar.setEnabled(u_.HabilitaJMenu(new Usuario.PerfilGrupo[]{A, E, V}, this.getUsuario().getPerfilGrupo(), mnCadastros));
        //</editor-fold>

        //<editor-fold defaultstate="collapsed" desc="Submenús IGM">
        mnIrradiacaoGlobal.setMnemonic(KeyEvent.VK_I);
        mnIrradiacaoGlobal.setEnabled(u_.HabilitaJMenu(new Usuario.PerfilGrupo[]{A, E}, this.getUsuario().getPerfilGrupo(), mnCadastros));
//        miIrradiacaoGlobalMesNovo.setEnabled(u_.HabilitaJMenu(new Usuario.PerfilGrupo[]{A, E, V}, this.getUsuario().getPerfilGrupo(), mnCadastros));
//        miIrradiacaoGlobalMesPesquisar.setEnabled(u_.HabilitaJMenu(new Usuario.PerfilGrupo[]{A, E, V}, this.getUsuario().getPerfilGrupo(), mnCadastros));
        //</editor-fold>

        //<editor-fold defaultstate="collapsed" desc="Submenús Usuários">
        mnUsuario.setMnemonic(KeyEvent.VK_O);
        mnUsuario.setEnabled(u_.HabilitaJMenu(new Usuario.PerfilGrupo[]{A}, this.getUsuario().getPerfilGrupo(), mnCadastros));
//        miUsuarioNovo.setEnabled(u_.HabilitaJMenu(new Usuario.PerfilGrupo[]{A, E, V}, this.getUsuario().getPerfilGrupo(), mnCadastros));
//        miUsuarioPesquisar.setEnabled(u_.HabilitaJMenu(new Usuario.PerfilGrupo[]{A, E, V}, this.getUsuario().getPerfilGrupo(), mnCadastros));
        //</editor-fold>

        mnRelatorios.setMnemonic(KeyEvent.VK_R);
        mnRelatorios.setEnabled(u_.HabilitaJMenu(new Usuario.PerfilGrupo[]{A, E}, this.getUsuario().getPerfilGrupo(), mnCadastros));
//        miListagemDeProjetos.setEnabled(u_.HabilitaJMenu(new Usuario.PerfilGrupo[]{A, E, V}, this.getUsuario().getPerfilGrupo(), mnCadastros));
        miListagemDeProjetos.setVisible(false);
        miListagemDeModulos.setEnabled(u_.HabilitaJMenu(new Usuario.PerfilGrupo[]{A, E, V}, this.getUsuario().getPerfilGrupo(), mnCadastros));
        miListagemDeInversores.setEnabled(u_.HabilitaJMenu(new Usuario.PerfilGrupo[]{A, E, V}, this.getUsuario().getPerfilGrupo(), mnCadastros));
        miSaldoEstoque.setEnabled(u_.HabilitaJMenu(new Usuario.PerfilGrupo[]{A, E, V}, this.getUsuario().getPerfilGrupo(), mnCadastros));
        miListagemDeUsuarios.setEnabled(u_.HabilitaJMenu(new Usuario.PerfilGrupo[]{A}, this.getUsuario().getPerfilGrupo(), mnCadastros));

        mnAlterarCredenciaisUsuario.setMnemonic(KeyEvent.VK_U);
        mnAlterarCredenciaisUsuario.setEnabled(u_.HabilitaJMenu(new Usuario.PerfilGrupo[]{A, E, V}, this.getUsuario().getPerfilGrupo(), mnCadastros));
        miAlterarCredenciaisUsuario.setMnemonic(KeyEvent.VK_H);
        miAlterarCredenciaisUsuario.setEnabled(u_.HabilitaJMenu(new Usuario.PerfilGrupo[]{A, E, V}, this.getUsuario().getPerfilGrupo(), mnCadastros));
        miFazerLogoff.setMnemonic(KeyEvent.VK_F);
        miFazerLogoff.setEnabled(u_.HabilitaJMenu(new Usuario.PerfilGrupo[]{A, E, V}, this.getUsuario().getPerfilGrupo(), mnCadastros));

        mnFecharSistema.setMnemonic(KeyEvent.VK_F);
        mnFecharSistema.setEnabled(u_.HabilitaJMenu(new Usuario.PerfilGrupo[]{A, E, V}, this.getUsuario().getPerfilGrupo(), mnCadastros));
        miSair.setMnemonic(KeyEvent.VK_S);
        miSair.setEnabled(u_.HabilitaJMenu(new Usuario.PerfilGrupo[]{A, E, V}, this.getUsuario().getPerfilGrupo(), mnCadastros));

    }
    /*
    private void HabilitaMenusItensDeAcordoComPerfilDoUsuarioOLD() {
//        mnAlterarCredenciaisUsuario.setEnabled(usuario.getPerfilGrupo() != Usuario.PerfilGrupo.Administrador);

//         Habilita menús para Administrador 
        boolean IsUSerAdm = (this.usuario.getPerfilGrupo() == (Usuario.PerfilGrupo.Administrador));
//         Menú Cadastros 
        mnCadastros.setMnemonic(KeyEvent.VK_C);
//        mnCadastros.setEnabled(false);
        mnModulos.setEnabled(IsUSerAdm);
//        miModuloNovo.setEnabled(false);
//        miModuloPesquisar.setEnabled(false);

        mnInversores.setEnabled(IsUSerAdm);
//        miInversorNovo.setEnabled(false);
//        miInversorPesquisar.setEnabled(false);

//        jSeparator2.setEnabled(false);
        mnCliente.setEnabled(IsUSerAdm);
//        miNovoCliente.setEnabled(false);
//        miPesquisarCliente.setEnabled(false);

        mnProjetoFotovoltaico.setEnabled(IsUSerAdm);
//        miProjetoNovo.setEnabled(false);
//        miProjetoPesquisar.setEnabled(false);

//        jSeparator1.setEnabled(false);
        mnIrradiacaoGlobal.setEnabled(IsUSerAdm);
//        miIrradiacaoGlobalMesNovo.setEnabled(false);
//        miIrradiacaoGlobalMesPesquisar.setEnabled(false);

        mnUsuario.setEnabled(IsUSerAdm);
//        miUsuarioNovo.setEnabled(false);
//        miUsuarioPesquisar.setEnabled(false);

//         Menú Relatórios 
        mnRelatorios.setMnemonic(KeyEvent.VK_R);
        mnRelatorios.setEnabled(IsUSerAdm);
//        miListagemDeProjetos.setEnabled(false);

//         Habilita menús para Engenheiro 
        if (this.usuario.getPerfilGrupo().equals(Usuario.PerfilGrupo.Engenheiro)) {
            mnModulos.setEnabled(true);
            mnInversores.setEnabled(true);
            mnProjetoFotovoltaico.setEnabled(true);
            mnIrradiacaoGlobal.setEnabled(true);
        } else if (this.usuario.getPerfilGrupo().equals(Usuario.PerfilGrupo.Vendedor)) {
            mnCliente.setEnabled(true);
        }

        mnFecharSistema.setMnemonic(KeyEvent.VK_S);
        mnAlterarCredenciaisUsuario.setMnemonic(KeyEvent.VK_U);
    }
     */
}
